blindModularity_BASC_RestOnly_CBSCMixed_OccMaskBasc6Only_RL_f

'LaunchCompareTopographies_RestOnly_CBSCMixed_OccMaskBasc6Only_RL_w_woRand'
LaunchCompareTopographies_RestOnly_CBSCMixed_OccMaskBasc6Only_RL_w_woRand

'LaunchAvgDiCe_RestOnly_CBSCMixed_OccMaskBasc6Only_RL_w_woRand'
LaunchAvgDiCe_RestOnly_CBSCMixed_OccMaskBasc6Only_RL_w_woRand

'LaunchCmpDiCe_RestOnly_CBSCMixed_OccMaskBasc6Onl_RL_w_woRand'
LaunchCmpDiCe_RestOnly_CBSCMixed_OccMaskBasc6Onl_RL_w_woRand

'LaunchAvg_DiCe_CrossScales_RestOnly_CBSCMixed_OccMaskBasc6Only_RL_w_woRand'
LaunchAvg_DiCe_CrossScales_RestOnly_CBSCMixed_OccMaskBasc6Only_RL_w_woRand

'LaunchCmpDiCe_RestOnly_CBSCMixed_OccMaskBasc6Only_RL_w_woRand_Omnibus'
LaunchCmpDiCe_RestOnly_CBSCMixed_OccMaskBasc6Only_RL_w_woRand_Omnibus

